# Decap CMS Configuration - public/admin/config.yml

# Backend connection (GitHub)
backend:
  name: github
  repo: johnnyhawk02/livpac-website
  branch: main
  base_url: https://livpac.pages.dev
  auth_endpoint: /api/auth

# Media folder path (relative to repo root)
media_folder: public/uploads/images
public_folder: /uploads/images

# Enable editorial workflow (allows drafts)
publish_mode: editorial_workflow

# Set site URL to ensure correct callback
site_url: https://livpac.pages.dev
display_url: https://livpac.pages.dev

# Collections
collections:
  - name: news
    label: News
    folder: src/content/news
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime, format: "YYYY-MM-DD" }
      - { label: Body, name: body, widget: markdown }

# Use local backend when running locally (comment out in production)
# local_backend: true

# Media files will be stored in the repo
# Ensure this path exists or adjust as needed
# media_folder: "public/uploads/images"
# public_folder: "/uploads/images"

# Enable editorial workflow (allows drafts)
# publish_mode: editorial_workflow

# Set site URL to ensure correct callback
# site_url: https://livpac.pages.dev
# display_url: https://livpac.pages.dev

# Define editable content types (Collections)
# collections:
#   # News Posts Collection
#   - name: "news" # Used in routes, e.g., /admin/#/collections/news
#     label: "News Posts" # Used in the UI
#     folder: "src/content/news" # The path to the folder where news files are stored
#     create: true # Allow users to create new files in this folder
#     slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template: YYYY-MM-DD-title.md
#     extension: "md" # File extension
#     format: "frontmatter" # Specifies that files have frontmatter
#     fields: # The fields for each news post
#       - { label: "Title", name: "title", widget: "string" }
#       - { label: "Publication Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
#       - { label: "Body", name: "body", widget: "markdown" }
#       - { label: "Featured Image", name: "image", widget: "image", required: false } 