# Decap CMS Configuration - public/admin/config.yml

# Backend connection (GitHub)
backend:
  name: github
  repo: johnnyhawk02/livpac-website # Updated GitHub repo path
  branch: main # Or whichever branch you deploy from (e.g., master)
  # base_url and auth_endpoint are needed for GitHub OAuth via a function
  # Update base_url with your live site URL (Cloudflare Pages URL for now)
  base_url: https://livpac.pages.dev 
  auth_endpoint: /api/auth # Path to the function we just created

# Media files will be stored in the repo
# Ensure this path exists or adjust as needed
media_folder: "public/uploads/images"
public_folder: "/uploads/images"

# Define editable content types (Collections)
collections:
  # News Posts Collection
  - name: "news" # Used in routes, e.g., /admin/#/collections/news
    label: "News Posts" # Used in the UI
    folder: "src/content/news" # The path to the folder where news files are stored
    create: true # Allow users to create new files in this folder
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template: YYYY-MM-DD-title.md
    extension: "md" # File extension
    format: "frontmatter" # Specifies that files have frontmatter
    fields: # The fields for each news post
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publication Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Body", name: "body", widget: "markdown" } 